### ISSUE TITLE
early observations

### ISSUE THREAD

**Issue by AngelMunoz** [alfonsogarciacaro/Elmish.Lit#2]
I've been having fun with this, I ended up with this sample repo

https://github.com/AngelMunoz/Flit

My only observation would be that it seems (due how to Lit works) if you create a standalone function that has internal state will not be rendered because render is only called when a change in the elmish state, my solution was to call each "page"  which in turn fires it's own elmish loop, I'm not sure if that's a good way to do it

this might make things cumbersome in the long run since anything that requires internal state kind of requires an elmish loop so far 

I'm still experimenting with it and if I come across more things I'll share them

**Comment by AngelMunoz** [comment]
I've been experimenting with the hooks provided by [Haunted](https://hauntedhooks.netlify.app/) ([Sample here](https://github.com/AngelMunoz/Fable.Haunted/blob/main/sample/src/Main.fs)) I think the single/multiple elmish looks can be solved by that in case it is a concern in scalability for some people
the only "downside" to haunted is that converts the render functions into web components so by default all styling needs to be done via ShadowDOM styling, either by using the `css` tag or I think the stylemap directive you added on the lit bindings

I'll keep exploring and see what else I can find or figure out

**Comment by alfonsogarciacaro** [comment]
Well, Elmish is not about components so it's ok that functions have no internal state. If you want to structure your app with components I guess the best approach is what you did: use web components, either with the help of an existing library or maybe creating some bindings ourselves.

> As an aside, for multi-page apps I just use the router in Fable.Elmish.Browser, though it's true some people don't like it because of the boilerplate needed.

I guess it's better to separate the packages by concerns, so for example Fable.Haunted doesn't need to take a dependency on Elmish. I've done it as follows:

- Fable.Lit: Bindings for lit-html
- React.Lit: Adapter to render React components out of a lit-html template
- Feliz.Engine.Lit: Ability to mix Feliz.Engine views (and styles) with lit-html templates... just because ;)
- Elmish.Lit: Use lit-html as the view function for an Elmish app.

**Comment by AngelMunoz** [comment]
I was just looking at Feliz.Engine.Lit (I was almost sure something like that would be possible 😆) man _you are very loco_ I could barely put out some crappy bindings and here you are doing feliz engine and react mixing along the way
be sure that I'll be checking the Lit stuff as well 😁

**Comment by AngelMunoz** [comment]
I ended doing some really basic dotnet templates, so people can get started with them I guess we'll keep these as betas for a while to see if they get picked up
https://www.nuget.org/packages/Fable.Lit.Templates/1.0.0-beta-002

I think we can close this now
